create extension if not exists pgcrypto;

create table if not exists listings (
  id uuid primary key default gen_random_uuid(),
  status text not null default '미방문',
  visit_date date,
  visit_time time,
  visited boolean not null default false,
  name text not null,
  article_number text,
  price integer,
  recent_deal integer,
  supply_area numeric(8, 2),
  exclusive_area numeric(8, 2),
  floor text,
  direction text,
  rooms integer,
  maintenance text,
  households text,
  parking text,
  realtor_phone text,
  description text,
  naver_url text unique,
  desired_price text,
  negotiable_price text,
  offer_price text,
  move_in_date text,
  move_in_memo text,
  checklist jsonb not null default '[]'::jsonb,
  ratings jsonb not null default '{}'::jsonb,
  memo text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create or replace function set_updated_at()
returns trigger as $$
begin
  new.updated_at = now();
  return new;
end;
$$ language plpgsql;

drop trigger if exists listings_set_updated_at on listings;

create trigger listings_set_updated_at
before update on listings
for each row
execute function set_updated_at();

insert into listings (
  status, name, article_number, price, recent_deal, supply_area, exclusive_area,
  floor, direction, rooms, maintenance, households, parking, realtor_phone,
  description, naver_url, move_in_date, checklist, ratings
)
values
  (
    '방문예정',
    '등촌코오롱 101동',
    '2628930751',
    83000,
    74500,
    88.52,
    59.99,
    '9/19층',
    '북서향',
    2,
    '15만원',
    '191세대 (해당 면적 45세대)',
    '203대 (세대당 1.06대)',
    '02-3661-1110',
    '입주, 올수리, 거실 작은방 확장, 방2, 증미역/가양역 이용. 지하 주차장 엘리베이터 연결.',
    'https://naver.me/G8ffF2Tq',
    '즉시입주 협의 가능',
    '[false,false,false,false,false,false,false,false]'::jsonb,
    '{"location":"","building":"","interior":"","price":"","preference":""}'::jsonb
  ),
  (
    '미방문',
    '삼성하나로 101동',
    '2629579499',
    80000,
    74000,
    79.99,
    59.26,
    '고/15층',
    '남동향',
    2,
    '16만원',
    '178세대 (해당 면적 96세대)',
    '130대 (세대당 0.73대)',
    '02-3663-4946 / 010-9198-4841',
    '급매, 로얄층/로얄라인, 2026년 10월 초순 입주 협의 가능. 염동초/염창중 학군, 강서둘레길·한강공원·안양천, 홈플러스·하나로마트, 9호선 염창급행역/등촌역 도보 10~15분.',
    'https://naver.me/5p00ihEe',
    '2026년 10월 초순 협의 가능',
    '[false,false,false,false,false,false,false,false]'::jsonb,
    '{"location":"","building":"","interior":"","price":"","preference":""}'::jsonb
  ),
  (
    '미방문',
    '벽산늘푸른 102동',
    '2628015513',
    90000,
    80800,
    79.72,
    59.97,
    '9/15층',
    '남서향',
    3,
    '10만원',
    '206세대 (해당 면적 105세대)',
    '173대 (세대당 0.83대)',
    '02-3664-0300 / 010-9133-4004',
    '남향, 샷시 포함 특올수리, 정상 입주 가능. 9호선 증미역 역세권, 한강공원·증미산 근처.',
    'https://naver.me/5WUUFLbF',
    '즉시입주',
    '[false,false,false,false,false,false,false,false]'::jsonb,
    '{"location":"","building":"","interior":"","price":"","preference":""}'::jsonb
  ),
  (
    '미방문',
    '벽산늘푸른 102동',
    '2624633836',
    86500,
    80800,
    79.72,
    59.97,
    '고/15층',
    '남향',
    3,
    '13만원',
    '206세대 (해당 면적 105세대)',
    '173대 (세대당 0.8대)',
    '02-3661-5905',
    '2027년 9월 30일 입주 협의 가능.',
    'https://naver.me/FG33itv4',
    '2027년 09월 30일 협의 가능',
    '[false,false,false,false,false,false,false,false]'::jsonb,
    '{"location":"","building":"","interior":"","price":"","preference":""}'::jsonb
  ),
  (
    '미방문',
    '벽산늘푸른 102동',
    '2628775648',
    85000,
    80800,
    79.72,
    59.97,
    '3/15층',
    '남서향',
    3,
    '15만원',
    '206세대 (해당 면적 105세대)',
    '173대 (세대당 0.83대)',
    '02-3661-5905',
    '남서향집. 즉시입주 협의 가능.',
    'https://naver.me/5RAADV79',
    '즉시입주 협의 가능',
    '[false,false,false,false,false,false,false,false]'::jsonb,
    '{"location":"","building":"","interior":"","price":"","preference":""}'::jsonb
  ),
  (
    '미방문',
    '등촌월드메르디앙 101동',
    '2629124575',
    100000,
    83300,
    75.8,
    59.79,
    '5/15층',
    '남동향',
    3,
    '18만원',
    '145세대 (해당 면적 55세대)',
    '146대 (세대당 1대)',
    '02-2659-0519',
    '최근 샷시 포함 특올수리, 확장형. CJ부지 개발호재, 지하주차장 엘리베이터 연결 편리.',
    'https://naver.me/xHEE9Umf',
    '즉시입주 협의 가능',
    '[false,false,false,false,false,false,false,false]'::jsonb,
    '{"location":"","building":"","interior":"","price":"","preference":""}'::jsonb
  ),
  (
    '미방문',
    '등촌현대2차 201동',
    '2626023501',
    82000,
    77500,
    105.79,
    84.95,
    '고/17층',
    '남동향',
    3,
    '20만원',
    '89세대 (해당 면적 31세대)',
    '79대 (세대당 0.88대)',
    '02-3662-9662',
    '소유주 확인 매물. 세안고 매매. 샤시교체, 내부 부분수리. 집 보실 분은 미리 연락 필요.',
    'https://naver.me/54KKdFOQ',
    '2027년 06월 하순 협의 가능',
    '[false,false,false,false,false,false,false,false]'::jsonb,
    '{"location":"","building":"","interior":"","price":"","preference":""}'::jsonb
  ),
  (
    '미방문',
    '등촌현대2차 201동',
    '2625903091',
    82000,
    77500,
    105.79,
    84.95,
    '15/17층',
    '남서향',
    3,
    '25만원',
    '89세대 (해당 면적 31세대)',
    '79대 (세대당 0.88대)',
    '02-3664-4886',
    '2027년 6월 중순 입주 협의 가능.',
    'https://naver.me/IDkkw0q5',
    '2027년 06월 중순 협의 가능',
    '[false,false,false,false,false,false,false,false]'::jsonb,
    '{"location":"","building":"","interior":"","price":"","preference":""}'::jsonb
  )
on conflict (naver_url) do update set
  status = excluded.status,
  name = excluded.name,
  article_number = excluded.article_number,
  price = excluded.price,
  recent_deal = excluded.recent_deal,
  supply_area = excluded.supply_area,
  exclusive_area = excluded.exclusive_area,
  floor = excluded.floor,
  direction = excluded.direction,
  rooms = excluded.rooms,
  maintenance = excluded.maintenance,
  households = excluded.households,
  parking = excluded.parking,
  realtor_phone = excluded.realtor_phone,
  description = excluded.description,
  move_in_date = excluded.move_in_date;
